# Generated by Django 5.2.11 on 2026-02-11 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0005_order_user_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='product_size',
        ),
        migrations.AddField(
            model_name='orderlineitem',
            name='license_type',
            field=models.CharField(blank=True, choices=[('personal', 'Personal'), ('commercial', 'Commercial'), ('extended', 'Extended')], max_length=20, null=True),
        ),
    ]
