# Generated by Django 5.2.11 on 2026-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_has_sizes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
        migrations.AddField(
            model_name='product',
            name='download_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='digital_products/'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_digital',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='license_type',
            field=models.CharField(choices=[('personal', 'Personal'), ('commercial', 'Commercial'), ('extended', 'Extended')], default='personal', max_length=20),
        ),
    ]
