# Generated by Django 5.2.11 on 2026-02-12 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_has_sizes_product_download_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='license_type',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price_commercial',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_extended',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='price_personal',
            field=models.DecimalField(decimal_places=2, default=10.0, max_digits=6),
            preserve_default=False,
        ),
    ]
