# Generated by Django 5.2.11 on 2026-02-12 14:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_license_type_remove_product_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_commercial',
            field=models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_extended',
            field=models.DecimalField(decimal_places=2, default=Decimal('75.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_personal',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=8),
        ),
        migrations.AlterField(
            model_name='product',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
    ]
